### ISSUE TITLE
Script System - AI

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#303]
This issue focused on the development of basic creature AI, allowing for combat to be implemented. The purpose is to capture all the items necessary to support Milestone 1.

##### Pick One
- [ ] Generic script system that allows for one, or many, inheritable Creature AI script(s)
- [ ] A prototype "script" tied to Non-Player Entities

##### Required
- [ ] Manages threat and target choice, and leashes in appropriate conditions; emits reset on leash to player(s) (#302)
- [ ] Manages navigation towards target, stopping at appropriate distance from target (#301)
- [ ] Cast a basic auto-attack to the target when in range (#308)

##### Optional
- [ ] Implement more advanced spell casting functionality, allowing for telegraphed attacks. Data is available for import from Jabbithole dump

#### Notes
- Rawaho has made extensive headway on a generic script system, so please check with him if you intend to write one. It'd be best to wait for his system to be implemented before tackling this ticket. 
The exception to that being if we've made no headway on this ticket and it's the remaining piece, we should perhaps consider creating a prototype script for Non-Player Entities.
