### ISSUE TITLE
Spell Rework - Todo list and order.

### ISSUE THREAD

**Issue by Rawaho** [NexusForever/NexusForever#475]
- [x] Update spells-v2-gr branch to latest game_rework branch.
- [ ] Refactor initial spell commit.
- [ ] Merge combat log changes.
- [ ] Investigate how the client generates spell tooltips for damage calculations.
- [ ] Merge damage calculation changes.
- [ ] Merge vital changes.
